repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
    -   id: isort
        name: isort (python)
    -   id: isort
        name: isort (cython)
        types: [cython]
    -   id: isort
        name: isort (pyi)
        types: [pyi]

-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3.8

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8

#-   repo: local
#    hooks:
#    -   id: pytest-cov
#        name: pytest coverage
#        language: system
#        entry: pytest --cov --cov-fail-under=0
#        types: [python]
