[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.env
  | scripts
  | _build
  | buck-out
  | build
  | dist
)/
'''
target-version = ['py38']
